apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-update-pods
roleRef:
  kind: ClusterRole
  name: pod-reader-updater
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fairwinds-pod-logger
    namespace: {{ .Release.Namespace | quote }}
    apiGroup: ""
