apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-read-update-pods"
roleRef:
  kind: ClusterRole
  name: "{{ .Release.Name }}-pod-reader-updater"
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-service-account"
    namespace: {{ .Release.Namespace | quote }}
    apiGroup: ""
