apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-pod-reader-updater"
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - update
      - watch
