apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-deployment"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-deployment"
    spec:
      serviceAccountName: "{{ .Release.Name }}-service-account"
      containers:
        - name: fairwinds-pod-logger
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
