apiVersion: apps/v1
kind: Deployment
metadata:
  name: fairwinds-pod-logger
  labels:
    app: fairwinds-pod-logger
spec:
  selector:
    matchLabels:
      app: fairwinds-pod-logger
  template:
    metadata:
      labels:
        app: fairwinds-pod-logger
    spec:
      serviceAccountName: fairwinds-pod-logger
      containers:
        - name: fairwinds-pod-logger
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          args: ["tail", "-f", "/dev/null"]
